X00TD/X01BD: drivers: media: platform: msm: camera_v2: sensor: flash: replace deprecated group_id with function The group_id member was replaced by function in struct media_entity starting from kernel 4.5.
Replace group_id with function to fix build error:

  error: no member named 'group_id' in 'struct media_entity'